# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def available_pods
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'MXParallaxHeader'
  pod 'MZFormSheetPresentationController'
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper', '~> 3.3'
  pod 'RxSwift', '~> 4.0'
  pod 'RealmSwift'
  pod 'Kingfisher', '=4.8.0'
  pod 'Moya', '= 10.0.2'
  pod 'SnapKit', '~> 4.0.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'ALLoadingView', '=1.1.4'
  pod 'IQKeyboardManager'
  pod 'SideMenuSwift' , '= 0.5.1'
  pod 'Malert', '= 3.0'
  pod 'FSCalendar'
  pod 'DZNEmptyDataSet'
  pod 'CRRefresh', '= 1.1.2'
  pod 'SkeletonView', '= 1.3'
  pod 'TKSubmitTransition', :git => 'https://github.com/entotsu/TKSubmitTransition.git', :branch => 'swift4'
end



target 'BaoVietOffice' do
    available_pods
end
